### ISSUE TITLE
Docker Unreal gives an error pyinit not defined

### ISSUE THREAD

**Issue by geevargs** [orig74/DroneSimLab#18]
Whenever I start unreal after following procedure for setup.
It works most of the time but sometimes it gives an error 
![image](https://user-images.githubusercontent.com/29235421/30087288-b1c88aee-9254-11e7-9786-8c37fd7149a5.png)

**Comment by geevargs** [comment]
I get this error sometimes when I try the render to texture game mode.


![image](https://user-images.githubusercontent.com/29235421/30088515-b2005b02-925b-11e7-92a5-a78d91512d2a.png)

**Comment by orig74** [comment]
For the "pyinit not defined" error. This is usually the case of running in a "stand alone" game mode. Make sure you select the  "viewport mode"  when you hit the play button in the editor. Also hit the stop button before you start the simulation that will make sure that the previous resources are properly cleaned.

**Comment by orig74** [comment]
As for the other texture game error. Please send me the steps you did to get this error?
(maybe open a different issue if it is unrelated to the previous one)

**Comment by geevargs** [comment]
I use the selected viewport not standalone viewport and use rendertotexture game mode.
Do you not use any gamemode and just play it directly.

**Comment by orig74** [comment]
I never used render to texture game mode.  There are two ways I used to run the simulation:
1. Direct selected viewport Play
2. As a Baked (stand alone) game (like some of the demos)

**Comment by geevargs** [comment]
I use the direct selected viewport and get the pyint not defined.
![image](https://user-images.githubusercontent.com/29235421/30128412-72229ada-92f7-11e7-8327-8b5274a6c404.png)

**Comment by geevargs** [comment]
Almost fixed...

![image](https://user-images.githubusercontent.com/29235421/30128940-35927764-92f9-11e7-9a04-3ae48002e716.png)

**Comment by geevargs** [comment]
It was some modfication I did...to the drone ip address...I want to send the udp packets from another ip address 10.0.1.30 with the lat,long,alt,pitch,roll and yaw.

**Comment by geevargs** [comment]
And I also noticed that if I dont kill the unreal engine,It causes the Pyint not found error.
