### ISSUE TITLE
The unreal engine docker crashes on execution

### ISSUE THREAD

**Issue by geevargs** [orig74/DroneSimLab#20]
I am trying  to use the unreal docker but I keep getting the Signal 11 or segmentation fault error...2 out 3 times i run unreal engine.
I assumed that it was because of the memory input so I built a smaller map similar to the demo but it still persists and is it the unreal engine.
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
./run.sh: line 9:  1357 Segmentation fault      (core dumped) Engine/Binaries/Linux/UE4Editor "/DroneLab/MyProject2/MyProject2.uproject" -nocore -project=/DroneLab/MyProject2/MyProject2.uproject
![image](https://user-images.githubusercontent.com/29235421/30995970-4c490b46-a472-11e7-93a6-11553945ab55.png)

**Comment by orig74** [comment]
Do you have two drones created in the environment?
It looks like it printed the HELLO COOL only once and probably exited on the second drone. you can check that by changing the config.n_drones to 1 instead of 2

**Comment by geevargs** [comment]
I am using only one drone the other one I am sending directly through my host.
I have modified it and will check if that has fixed it.

**Comment by geevargs** [comment]
Still crashes frequently....
![image](https://user-images.githubusercontent.com/29235421/30996951-4b7e1ad8-a479-11e7-85ec-c04dc7bb172e.png)

**Comment by orig74** [comment]
try to run it without sending anything from your host, is it still crashes?

**Comment by geevargs** [comment]
It happens when I click play and fails regardless of where I send the data from whether its the SITL image or from my host machine.

**Comment by geevargs** [comment]
I tried running it with out any data coming into it from any source and it crashed on play.
My host sends data to unreal at 5Hz and Sitl sends at 30 Hz but I tried running unreal As Is and it still crashed and gave signal 11.

**Comment by orig74** [comment]
Updated to a newer version of unreal engine.
