### ISSUE TITLE
Docker for Windows

### ISSUE THREAD

**Issue by availn** [orig74/DroneSimLab#27]
I'm supposing that this will not run with Docker for Windows without some modifications. Besides handling the graphics drivers and X11, would there be something else that would need to be changed?

**Comment by orig74** [comment]
Hi, 
I guess it is possible but it will require a lot of modifications. If you need the host to be windows I think it is worth trying is to use virtual box with pass threw for the graphics card and install Ubuntu 16.04 in VirtualBox and dronesimlab inside it.

**Comment by R055A** [comment]
I am using a Windows 10 and Linux Mint 18.3 dual installment. 100 GB of space was required in the /root folder for installing the DroneSimLab framework.
