### ISSUE TITLE
Disbale game view window

### ISSUE THREAD

**Issue by ykhedar** [orig74/DroneSimLab#30]
Hi, is there a way to disable the game view window? I am running the demo - px4_gazebo.

Thanks,  

ykhedar

**Comment by R055A** [comment]
Enlarge the other window that you prefer so that it covers the game view window?

**Comment by ykhedar** [comment]
Visibility is less of a problem. Since I am not doing anything in this window and it is still being rendered, it is using some computational power (not sure how large or small). So I was wondering if there was a way to switch it off. :)

**Comment by orig74** [comment]
If you are using the game mode (packed game) you can change the game parameters in the GameUserSettings.ini file under /LinuxNoEditor/testprj7_14_4/Saved/Config/LinuxNoEditor/. I don't know if you can disable it completely but you can change the screen resolution to something smaller and this maybe will save you some CPU usage. In the Unreal Editor, you can change the rendering parameters and also save some more CPU Usage.

**Comment by ykhedar** [comment]
Thanks @orig74 I will try this suggestion. 

Edited:
This works but the CPU load is unchanged. It seems that the game engine it self is demanding a high load, which would make sense. Would love to know your points.
