### ISSUE TITLE
Commands do not work on my laptop

### ISSUE THREAD

**Issue by gonzaloaguilarjimenez** [orig74/DroneSimLab#32]
Good afternoon Ori, 

I am Gonzalo Aguilar, doing a PhD on Robotics (Neural Networks) in Spain.

To be able to simulate my NN, I need to combine several programs. The programs to combine are: 
- UE4 
- ROS
- PX4
- AirSim

In the basis of my project i will try to do a simulation of my NN on a SITL on UE4, sensors simulated on PX4 and ROS. Later I will do a real test with a HITL using a real drone but my UE4 environment and finally a test on real environment. 

To check compatibility my Hardware is:
- Intel i7 7700 HQ
- SSR 2050 Mb/s
- Nvidia Gforce GTX 1070

My software is: 
- Ubuntu 16.04.03 LTS

I have already installed by my own and it is already working a combination of: 
- UE4.17.2
- PX4
- XBOX 360 Gamepad
- AirSim

Now I will start explaining my main problems when I try to install DroneSimLab.

![unnamed](https://user-images.githubusercontent.com/35638894/38321955-481956a6-3839-11e8-93d9-607e0f27bf92.png)

![unnamed 1](https://user-images.githubusercontent.com/35638894/38322020-7b500970-3839-11e8-8c23-2ed9bb849eb3.png)

In these two images we can see: 
1. the result of the docker images after following the process given on DroneSimLab
2. the result when I run the first demo given on Easy Start by running the commands
      $  cd demos/px4_gazebo
      $ ./runtmux_game_docker.sh

I do not really know what the problem is, but I am stucked on this since long time ago and I do not know how to go on.

I hope you can help me.

Thanks in advance.

Best regards.

**Comment by orig74** [comment]
Hi,
please show me the output after running 
`./build.py`
And also after the build, you should have a few files in the form of `/tmp/dbuild-%s.log`
These are the files generated after each docker build for each image.
add them as an attachment

**Comment by gonzaloaguilarjimenez** [comment]
Hello, 

This is what I got after running ./build.py

![image](https://user-images.githubusercontent.com/35638894/38335735-aedf77f0-385f-11e8-9a77-214b35896727.png)

Nothing similar...

**Comment by orig74** [comment]
Hi,
found the problem
The assert is because the script cant access the games demo path on the web. the game demo is on the university servers and they recently changed the access policy without letting me know. I am working on it now.

**Comment by orig74** [comment]
Fixed,
Please pull the latest version, I updated the build script.

**Comment by gonzaloaguilarjimenez** [comment]
Hello, 

I was able to install every docker image except that of UE4. I will try it again and let you know.

I wonder if it is possible that I use my own UE4 project with your DroneSimLab App. Could you pleae inform me how to do it? 

Thanks a lot.

Best regards.

**Comment by orig74** [comment]
Yes, you can use your project. follow carefully the wiki page [link](https://github.com/orig74/DroneSimLab/wiki/Setup-of-the-Unreal-Engine-4-for-the-demos)
especially the part that initializes the PROJECT_FILES_DIR variable. this is the **parent** folder of your project. This directory will be mapped inside the docker container to `/project_files`  folder.
The make sure you did it correctly after running the UnrealEngine container you can run:
```
cd /project_files
ls
```
you should see you project folder at the output

**Comment by orig74** [comment]
As for the unreal engine failure, you can attach the installation log file in:
```
/tmp/dbuild-unreal_engine_4.log
```

**Comment by gonzaloaguilarjimenez** [comment]
Good morning,

I was finally able to install the UE4 image as you can see in the right terminal window, it looks as follows when I run the demo.

![image](https://user-images.githubusercontent.com/35638894/38466233-8b70f90a-3b26-11e8-8710-2ab747406c18.png)

However, when running the demo as seen before, there is an error which I mark in white on the left window ( ros image is shown as not existing, while in the docker images it seems to be perfectly installed)

Actually after I have seen all your demos on youtube, when you run the app, there are several terminal windows loaded on the screen, but when I run it, there is only one window as shown.

Am I doing anything wrong or this is normal? 

Thanks a lot.

Best regards.

**Comment by R055A** [comment]
It sometimes doesn't run 100% the first time. It could take more than two runs sometimes in my experiences earlier this year.

There was also a 'ros_image_indigo' that has been removed from the build earlier this year.

You can see it showing in the repository column of the docker images example on the wiki 'Easy start'

**Comment by gonzaloaguilarjimenez** [comment]
I have run it multiple times just to check as you said ("could take more than two runs") but still the result is 'not existing the ros image'.

**Comment by R055A** [comment]
Maybe you need to reinstall the ros_image_kinetic. I had this issue. It did not install 100% although it showed as installed. To reinstall just kinetic, run '../build' from the kinetic directory.

**Comment by gonzaloaguilarjimenez** [comment]
I did as you indicated... as well I installed the ros_indigo image but as you can see there is no good result.  

Besides, the "run_tmux_ros_px4.sh" is shown as not existing...

![image](https://user-images.githubusercontent.com/35638894/38468732-5ecbcdde-3b4a-11e8-87d3-6145cba9d1fb.png)

**Comment by orig74** [comment]
Hi,
Can you explain what is the ros_image_1 folder (under dockers)? 
Did you create it?

**Comment by gonzaloaguilarjimenez** [comment]
I did not create it. Previously to installation I deleted all my docker images. 

I think it must be included in the DroneSimLab.

**Comment by orig74** [comment]
well, it's not there. have a look at this folder:
[docker folder](https://github.com/orig74/DroneSimLab/tree/master/dockers)

**Comment by gonzaloaguilarjimenez** [comment]
Good afternoon again, 

I am trying to reconnect everything with another demo:

![image](https://user-images.githubusercontent.com/35638894/38511474-99959588-3c28-11e8-9f2c-2e172b1f9f2e.png)

On the image you can see in the terminal top-left containers and images on my dockers, in the terminal to p-right the result when I run both ./run_image.sh and ./attach.sh. Finally center-down terminal you can see the result when I run the : 

~/DroneSimLab/demos/px4_gazebo$ runtmux_full_docker.sh

Several procceses are open in window terminals top-right and center-down but i cannot see any result.

**Comment by orig74** [comment]
The Unreal engine editor needs to be open with the project you are working on when running full Demo (not packed game).
You should run the Unreal Engine from the container e.g.:
```
cd /local/UnrealEngine
Engine/Binaries/Linux/UE4Editor -nocore
```

**Comment by gonzaloaguilarjimenez** [comment]
Good night again, 

I had to unninstall the docker images and now when I am trying to re-install them again, this is the result with the ROS images:

![image](https://user-images.githubusercontent.com/35638894/38834620-45988cc8-41c9-11e8-8558-a54d1a1f7656.png)

After doing everything writen on your site, the result is shown, even after running the command you can see on the last line of the right terminal.

Can you please let me know if something has changed on the server?

Thanks a lot.

Best regards.

**Comment by gonzaloaguilarjimenez** [comment]
Maybe this helps: 

![image](https://user-images.githubusercontent.com/35638894/38835781-66ab02f8-41cc-11e8-875f-5557a90d67c2.png)

**Comment by orig74** [comment]
try building the images by running the build script with the nocache flag:
```
python build.py --nocache
```

**Comment by gonzaloaguilarjimenez** [comment]
Hello again, 

I did as indicated and here I show the result:

![image](https://user-images.githubusercontent.com/35638894/38898603-b7fb8b86-4295-11e8-9fc6-0a50e40b1fd2.png)

Any advise? 

Thanks again.

**Comment by orig74** [comment]
Pull the latest version.
It should be ok now.

**Comment by gonzaloaguilarjimenez** [comment]
Done. 
I will try to run my UE4 project within the next days and inform you.
Thanks a lot.
