### ISSUE TITLE
Unreal Simulation Not Working_Command window Running perfect but no display in Unreal Editor

### ISSUE THREAD

**Issue by sami8857** [orig74/DroneSimLab#34]
If i run only the (./runtmux_game_docker.sh) in px4_gazebo demo It works and show simulation window of gazebo and i can navigate also but the (./runtmux_full_docker.sh) is not working and no unreal engine simulation window opens. Similarly for the other demos underwater and bluerov  (./runtmux_full_docker.sh) it is not working. Everything on the tmux command window seems to be Ok but no unreal simulation window opens
My ultimate goal is to run the demo of underwater and bluerov and further modify them but they are not working. Can you please help regarding that. Following are the screenshots.

For px4_gazebo demo  (./runtmux_game_docker.sh)   This demo is working  fine.

![gazebo](https://user-images.githubusercontent.com/10168533/48237829-e1457980-e40b-11e8-928e-84f0bab1620f.png)

![gazebo1](https://user-images.githubusercontent.com/10168533/48237841-ee626880-e40b-11e8-8cc2-895d2fa0eb91.png)

For px4_gazebo demo  (./runtmux_full_docker.sh)   This demo is not working. 

![px4_gazebo_full2](https://user-images.githubusercontent.com/10168533/48237897-236ebb00-e40c-11e8-9f54-8954a0144496.png)

![px4_gazebo_full1](https://user-images.githubusercontent.com/10168533/48237904-2a95c900-e40c-11e8-9e55-99ee6c034a6e.png)

Similarly others like underwater and bluerov are not working too. No unreal simulation window opens where i can add (PyServer Tick Actor) and it seems to me that project files of demos related to unreal editor are not present because of which no graphical simulation opens in unreal.

For UnderWater demo (./runtmux_full_docker.sh)     Not Working

![underwaqter](https://user-images.githubusercontent.com/10168533/48238088-08e91180-e40d-11e8-9469-4bf85a0913ed.png)

![underwater1](https://user-images.githubusercontent.com/10168533/48238093-0be40200-e40d-11e8-8500-f2ef81ea1d16.png)

For bluerov (./runtmux_full_docker.sh)               Not Working

![bluerov1](https://user-images.githubusercontent.com/10168533/48238144-3b930a00-e40d-11e8-9f33-f9cbea5f8bdb.png)

this one even doesnot have the unreal text on the bottom left as in other demos instead 1:bash* is written. Also (./runtmux_game_docker.sh) is also not running for bluerov and same window opens as in this above screenshot.

ThankYou.

**Comment by orig74** [comment]
Hi,
Only the ./runtmux_game_docker.sh is currently part of DroneSimLab which is based on a packed game I created from my project. 
The ./runtmux_full_docker.sh is meant to be used as a template to show you how to run when you have an unreal project created.
As for the underwater demo, I'll check.

**Comment by orig74** [comment]
In the installation directory run the folowing code to get my version of ardupilot
```
cd ardupilot
git pull https://github.com/orig74/ardupilot.git
``` 
run the demo again

**Comment by RobertWZ** [comment]
can this run on ubuntu 18.04?

**Comment by orig74** [comment]
haven't tested it on 18.04 but it should work.
