### ISSUE TITLE
Streaming video over to QGC

### ISSUE THREAD

**Issue by Jaeyoung-Lim** [orig74/DroneSimLab#36]
Hi, this is a pretty cool project!

I found this script which seems to be streaming video over to the ground station: https://github.com/orig74/DroneSimLab/blob/710ee903b2c8b307de65c2e278a8f119484c00ad/demos/bluerov/ue4_image_bridge.py

But I also see a lot of debug scripts inside. Is this currently a functional script with the correct configs?

**Comment by orig74** [comment]
Hi,
Are you trying to run the [bluerov](https://github.com/orig74/DroneSimLab/wiki/BlueROV-simulation) demo? 
the script should work and transmit the video to the QGC
