### ISSUE TITLE
BlueRov: Collisions of the submarine with the ocean floor objects

### ISSUE THREAD

**Issue by lazydroid** [orig74/DroneSimLab#41]
While the UE camera can detect collisions with the objects on the ocean floor, the BlueROV model passes through the objects. Is there any chance to get this somehow fixed, or get a quick explanation how I can do that myself?

Thanks!

**Comment by orig74** [comment]
Hi, currently it's not supported. The main focus of this simulation is the visual interaction. It is possible to integrate ray tracing capabilities under the submodule UE4PythonBridge.
