### ISSUE TITLE
PROJECT_FILES_DIR & PROJECT_NAME 

### ISSUE THREAD

**Issue by orig74** [orig74/DroneSimLab#6]
need to think what to do with those environment variables define in the tmux scripts and the run image scripts

**Comment by ykhedar** [comment]
Hi, I was trying to run the px4_gazebo demo with the editor. But it seems there are no project files in the project directory

> PROJECT_FILES_DIR=/local/learn/ur4

Does one have to create the game files and put it into this directory or I am missing something?

Thanks for your help. :)

**Comment by orig74** [comment]
When you are using the Unreal Engine Editor, the idea is that you create your own virtual environment project yourself and add the dronesimlab components to it with the instructions given by the dronesimlab wiki.
